# Site settings
title: "Jashwanth Bavandlapalli"
description: "A Web Page For Jashwanth Bavandlapalli"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jashwanth Bavandlapalli"
resume_title:                   "Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "bavandlapallijashwanth@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 9059130398"
resume_contact_address:         "Hyderabad, India"

resume_header_contact_info:     "Hayatnagar - Hyderabad, Telangana • 501-505 • bavandlapallijashwanth.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> I am a sophomore in Instrumentation Engineering at Vignan Institute of Technology and Science, I bring a strong programming background, a
passion for mathematics, and expertise in web development. Seeking a summer internship in software development, I thrive on hands-on
experience and possess a knack for swiftly learning and applying new skills with precision and innovation.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jashwanthbavandlapalli"
  resume_twitter_url:           "https://x.com/JBavandlapalli"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "www.linkedin.com/in/jashwanthbavandlapalli"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jashwanthbavandlapalli.github.io/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
